# Change these first
owner: ferry-develops # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository
user-agent: treeot

assignees: # Users to assign downtime issues (optional)
  - treeot

sites:
  - name: Ferry Bot
    url: $FERRY_BOT
  - name: Site
    url: $SITE
  - name: Documentation
    url: $DOCUMENTATION
  - name: Phishing Database
    url: $PHISHING_DATABASE
  - name: Mojang API
    url: $MOJANG_API

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ferry.cf
  theme: ocean
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.discordapp.com/avatars/941859797551177809/8062714b6b25d7e2560bbbab8ba226ed.png
  name: Ferry Status Page
  introTitle: "**Ferry Bot Status**"
  introMessage: " "
  navbar:
    - title: Documentation
      href: https://docs.ferry.cf/
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ferry-develops
    - title: Discord
      href: https://ferry.cf/support

i18n:
  footer: Powered by [Ferry Bot](https://ferry.cf/invite),
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration